# Generated by Django 3.0.4 on 2020-08-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_augmenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illustrationset',
            name='illustrationList',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='uploads/'),
        ),
    ]
