# Generated by Django 3.0.4 on 2020-08-09 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('color_augmenter', '0003_auto_20200809_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illustrationset',
            name='illustrationList',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='uploads/'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('illustration_set', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='color_augmenter.IllustrationSet')),
            ],
        ),
    ]
