# Generated by Django 3.0.4 on 2020-08-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_augmenter', '0005_auto_20200809_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='uploads/'),
        ),
    ]
