# Generated by Django 3.0.4 on 2021-08-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ForensicsData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
                ("modified", models.DateField(auto_now=True)),
                ("forensics_data_text", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, max_length=256, null=True, upload_to="uploads/"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
